import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BugSnag Next.js Example App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-100 bg-no-repeat`}>
        <nav className="bg-inherit">
          <Link href="https://www.bugsnag.com" className="text-zinc-900 px-10">BugSnag</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
