source 'https://rubygems.org'

#gem 'bugsnag-maze-runner', git: 'https://github.com/bugsnag/maze-runner', tag: 'v6.2.1'

# Use a branch of Maze Runner
gem 'bugsnag-maze-runner', git: 'https://github.com/bugsnag/maze-runner', branch: 'tms/use-maze-check'

# Locally, you can run against Maze Runner branches and uncommitted changes:
#gem 'bugsnag-maze-runner', path: '../../../maze-runner'
