agents:
  queue: "opensource"

steps:

  #
  # Java 11 Android builder base - used by React Native and React Native CLI (< 0.73)
  #
  - label: ":docker: Build Java 11 Android Builder base image"
    key: "android-builder-base-java-11"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v4.12.0:
          build: android-builder-base-java-11
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  android-builder-base-java-11:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base-java-11
      - docker-compose#v4.12.0:
          push: android-builder-base-java-11:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base-java-11
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Upload full React Native pipelines
  #
  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: FULL REACT NATIVE (ANDROID) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
    - "publish-js"
    - "android-builder-base-java-11"
    agents:
      queue: "macos"
    timeout_in_minutes: 5
    commands:
      - buildkite-agent pipeline upload .buildkite/full/react-native-android-pipeline.full.yml

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: FULL REACT NATIVE (IOS) STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
    - "publish-js"
    agents:
      queue: "macos"
    timeout_in_minutes: 5
    commands:
      - buildkite-agent pipeline upload .buildkite/full/react-native-ios-pipeline.full.yml

  - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: REACT NATIVE CLI STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
    depends_on:
      - "publish-js"
    agents:
      queue: "macos"
    timeout_in_minutes: 5
    commands:
      - buildkite-agent pipeline upload .buildkite/full/react-native-cli-pipeline.full.yml

  #
  # Trigger Expo pipelines
  #
  - label: "@bugsnag/expo latest"
    depends_on: "publish-js"
    trigger: "bugsnag-expo"
    build:
      branch: "v52/next"
      env:
        BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
        BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
        # a branch name that's safe to use as a docker cache identifier
        BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"

  - label: "@bugsnag/expo v51/next"
    depends_on: "publish-js"
    trigger: "bugsnag-expo"
    build:
      branch: "v51/next"
      env:
        BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
        BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
        # a branch name that's safe to use as a docker cache identifier
        BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"

  - label: "@bugsnag/expo v50/next"
    depends_on: "publish-js"
    trigger: "bugsnag-expo"
    build:
      branch: "v50/next"
      env:
        BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
        BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
        # a branch name that's safe to use as a docker cache identifier
        BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"
