steps:

  - group: "React Native (Android) Tests"
    steps:
      #
      # Test fixtures
      #
      - label: ":android: Build RN 0.60 apk"
        key: "rn-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          LANG: "en_US.UTF-8"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.60.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.66 apk"
        key: "rn-0-66-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.66"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.66.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.67 apk"
        key: "rn-0-67-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.67"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.67.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.68 Hermes apk"
        key: "rn-0-68-hermes-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.68-hermes"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.68-hermes.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.69 apk"
        key: "rn-0-69-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.69"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.69.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.71 (Old Arch) apk"
        key: "rn-0-71-old-arch-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.71"
          RN_NEW_ARCH: "false"
          ARTEFACT_NAME: "rn0.71-old-arch"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.71-old-arch.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build RN 0.71 (New Arch) apk"
        key: "rn-0-71-new-arch-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.71"
          RN_NEW_ARCH: "true"
          ARTEFACT_NAME: "rn0.71-new-arch"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.71-new-arch.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build react-navigation 0.60 apk"
        key: "react-navigation-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          JS_SOURCE_DIR: "react_navigation_js"
          ARTEFACT_NAME: "r_navigation_0.60"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/r_navigation_0.60.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build react-navigation 0.69 apk"
        key: "react-navigation-0-69-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.69"
          JS_SOURCE_DIR: "react_navigation_js"
          ARTEFACT_NAME: "r_navigation_0.69"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/r_navigation_0.69.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build react-native-navigation 0.60 apk"
        key: "react-native-navigation-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          JS_SOURCE_DIR: "react_native_navigation_js"
          ARTEFACT_NAME: "r_native_navigation_0.60"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/r_native_navigation_0.60.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":android: Build react-native-navigation 0.66 apk"
        key: "react-native-navigation-0-66-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.66"
          JS_SOURCE_DIR: "react_native_navigation_js"
          ARTEFACT_NAME: "r_native_navigation_0.66"
        plugins:
          - docker-compose#v4.12.0:
              pull: react-native-android-builder
              run: react-native-android-builder
        artifact_paths:
          - build/r_native_navigation_0.66.apk
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      #
      # End-to-end tests
      #
      - label: ":bitbar: :android: RN 0.60 Android end-to-end tests"
        depends_on: "rn-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.60.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.66 Android end-to-end tests"
        depends_on: "rn-0-66-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.66.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.66.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.67 Android end-to-end tests"
        depends_on: "rn-0-67-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.67.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.67.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.69 Android end-to-end tests"
        depends_on: "rn-0-69-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.69.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.69.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.68 (Hermes) Android end-to-end tests"
        depends_on: "rn-0-68-hermes-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.68-hermes.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.68-hermes.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.71 (Old Arch) Android 12 end-to-end tests"
        depends_on: "rn-0-71-old-arch-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.71-old-arch.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.71-old-arch.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager

      - label: ":bitbar: :android: RN 0.71 (New Arch) Android 12 end-to-end tests"
        depends_on: "rn-0-71-new-arch-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.71-new-arch.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.71-new-arch.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager

      - label: ":bitbar: :android: react-navigation 0.60 Android end-to-end tests"
        depends_on: "react-navigation-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_navigation_0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/r_navigation_0.60.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: react-navigation 0.69 Android end-to-end tests"
        depends_on: "react-navigation-0-69-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_navigation_0.69.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/r_navigation_0.69.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: react-native-navigation 0.60 Android end-to-end tests"
        depends_on: "react-native-navigation-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_native_navigation_0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/r_native_navigation_0.60.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager

      - label: ":bitbar: :android: react-native-navigation 0.66 Android end-to-end tests"
        depends_on: "react-native-navigation-0-66-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_native_navigation_0.66.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/r_native_navigation_0.66.apk
              - --app-activity=com.reactnative.MainActivity
              - --app-package=com.reactnative
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar'
        concurrency_method: eager
