version: "2"
checks:
  method-complexity:
    config:
      threshold: 7
  return-statements:
    enabled: false
  method-lines:
    config:
      threshold: 30
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- "test/"
- "browser/test"
- "**/*.test.js"
- "examples/"
- "features/fixtures"
