FROM node:10-alpine

RUN apk add --no-cache --update ruby-full ruby-bundler ruby-dev git build-base libffi-dev curl-dev bash

# All of this is required for browserstack local on alpine
RUN apk add --no-cache libc6-compat

WORKDIR /usr/src/app

COPY packages/browser/Gem* ./
RUN bundle

COPY package*.json ./
RUN npm install

COPY . /usr/src/app/

RUN npx lerna bootstrap
RUN npm run build
WORKDIR packages/browser
