# CI test image for unit/lint/type tests
FROM node:10-alpine as ci

RUN apk add --update bash

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY package lerna.json ./
RUN npx lerna bootstrap

COPY babel.config.js tslint.json bin ./
RUN npm run build
