FROM node:10-alpine

RUN apk add --update ruby-full ruby-bundler ruby-dev git build-base libffi-dev curl-dev bash

WORKDIR /usr/src/app

COPY packages/browser/Gem* ./
RUN bundle

COPY package*.json ./
RUN npm install

COPY . /usr/src/app/

RUN npx lerna bootstrap
RUN npm run build
