source 'https://rubygems.org'

gem 'cocoapods'

gem 'bugsnag-maze-runner', '~>8.0'

# Use a branch of Maze Runner
#gem 'bugsnag-maze-runner', git: 'https://github.com/bugsnag/maze-runner', branch: 'tms/use-maze-check'

# Locally, you can run against Maze Runner branches and uncommitted changes:
#gem 'bugsnag-maze-runner', path: '../maze-runner'
