source 'https://rubygems.org'

gem 'cocoapods'

# A reference to Maze Runner is only needed for running tests locally and if committed it must be
# portable for CI, e.g. a specific release.  However, leaving it commented out would mean quicker CI.
gem 'bugsnag-maze-runner', git: 'https://github.com/bugsnag/maze-runner', tag: 'v5.2.0'

# Locally, you can run against Maze Runner branches and uncommitted changes:
#gem 'bugsnag-maze-runner', path: '../maze-runner'

