steps:

  - group: "Browser Tests"
    steps:
      - label:  ":docker: Maze Runner image - BitBar browsers"
        key: "browser-maze-runner-bb"
        timeout_in_minutes: 20
        plugins:
          - artifacts#v1.5.0:
              download: min_packages.tar
          - docker-compose#v4.12.0:
              build:
                - browser-maze-runner-bb
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from:
                - browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-browser-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push:
                - browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-browser-${BRANCH_NAME}

      - label:  ":docker: Maze Runner image - BrowserStack browsers"
        key: "browser-maze-runner-bs"
        timeout_in_minutes: 20
        plugins:
          - artifacts#v1.5.0:
              download: min_packages.tar
          - docker-compose#v4.12.0:
              build:
                - browser-maze-runner-bs
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from:
                - browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-browser-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push:
                - browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-browser-${BRANCH_NAME}

      #
      # BitBar tests
      #
      - label: ":bitbar: {{matrix}} Browser tests"
        matrix:
          - firefox_latest
          - chrome_latest
          - edge_latest
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bb
            run: browser-maze-runner-bb
            use-aliases: true
            command:
              - --farm=bb
              - --browser={{matrix}}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 5
        concurrency_group: "bitbar-web"
        concurrency_method: eager

      - label: ":bitbar: ie_11 Browser tests"
        depends_on: "browser-maze-runner-bb"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            service-ports: true
            use-aliases: true
            command:
              - --farm=bb
              - --browser=ie_11
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 5
        concurrency_group: "bitbar-web"
        concurrency_method: eager
        env:
          HOST: "localhost" # IE11 needs the host set to localhost for some reason

      #
      # BrowserStack tests
      #
      - label: ":browserstack: {{matrix}} tests"
        matrix:
          - chrome_43
          - chrome_72
          - ie_8
          - ie_9
          - ie_10
          - edge_17
          - safari_10
          - safari_16
          - iphone_7   # iOS 10
          - iphone_13
          - android_s8 # Android 7
          - firefox_78
        depends_on: "browser-maze-runner-bs"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{matrix}}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 2
        concurrency_group: "browserstack"
        concurrency_method: eager
