steps:
  - label:  ':docker: Build expo publisher'
    key: "expo-publisher"
    timeout_in_minutes: 30
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.7.0:
          build: expo-publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BRANCH_NAME}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest
      - docker-compose#v3.7.0:
          push:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BRANCH_NAME}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest

  - label:  ':docker: Publish expo app'
    key: "publish-expo-app"
    depends_on: "expo-publisher"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-highpower"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.7.0:
          run: expo-publisher

  - label: ':docker: Build expo maze runner image'
    key: "expo-maze-runner-image"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.7.0:
          build: expo-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - label:  ':docker: Build expo APK builder'
    key: "expo-android-builder"
    timeout_in_minutes: 40
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.7.0:
          build: expo-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BRANCH_NAME}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest
      - docker-compose#v3.7.0:
          push:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BRANCH_NAME}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - label:  ':docker: Build expo APK'
    key: "build-expo-apk"
    depends_on:
      - "publish-expo-app"
      - "expo-android-builder"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-highpower"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.apk
    plugins:
      - docker-compose#v3.7.0:
          run: expo-android-builder
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - label: ':docker: Build expo IPA'
    key: "build-expo-ipa"
    depends_on:
      - "publish-expo-app"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-mac-expo"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.ipa
    commands:
      - test/expo/scripts/build-ios.sh

  - label: ':runner: expo Android 9'
    depends_on:
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_9_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 12'
    depends_on:
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_12
          - --a11y-locator
          - --appium-version=1.16.0
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - block: "Trigger full test suite"
    key: "trigger-full-suite"

  - label: ':runner: expo Android 8'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_8_1
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --appium-version=1.18.0
          - --capabilities={"appWaitForLaunch":"false"}
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    soft_fail:
      - exit_status: "*"

  - label: ':runner: expo Android 7'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_7_1
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo Android 6'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_6_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo Android 5'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_5_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 11'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_11
          - --a11y-locator
          - --appium-version=1.16.0
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 10'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v3.7.0:
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_10
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --resilient
    concurrency: 6
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
