steps:
  - label:  ':docker: Build expo publisher'
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v2.6.0:
          build: expo-publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BUILDKITE_BRANCH}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest
      - docker-compose#v2.6.0:
          push:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BUILDKITE_BRANCH}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest

  - label: ':docker: Build expo maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build: expo-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
      - docker-compose#v2.6.0:
          push:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BUILDKITE_BRANCH}
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - label:  ':docker: Build expo APK builder'
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v2.6.0:
          build: expo-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BUILDKITE_BRANCH}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest
      - docker-compose#v2.6.0:
          push:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BUILDKITE_BRANCH}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - wait

  - label:  ':docker: Publish expo app'
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v2.6.0:
          run: expo-publisher

  - wait

  - label:  ':docker: Build expo APK'
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.apk
    plugins:
      - docker-compose#v2.6.0:
          run: expo-android-builder
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - label: ':docker: Build expo IPA'
    agents:
      queue: "opensource-mac"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.ipa
    commands:
      - test/expo/scripts/build-ios.sh

  - wait

  - label: 'expo Android 9'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_9"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo Android 8'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_8"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo Android 7'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_7"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo Android 6'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_6"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo Android 5'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.apk"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "ANDROID_5"
      APP_LOCATION: "build/output.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo iOS 10'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_10"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo iOS 11'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_11"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'expo iOS 12'
    plugins:
      artifacts#v1.2.0:
        download: "build/output.ipa"
      docker-compose#v2.6.0:
        run: expo-maze-runner
        use-aliases: true
    env:
      DEVICE_TYPE: "IOS_12"
      APP_LOCATION: "build/output.ipa"
    concurrency: 5
    concurrency_group: 'browserstack-app'
