steps:

  - label:  ':docker: Build node maze runner image'
    key: "node-maze-runner-image"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.3.0:
          download: min_packages.tar
          build: ${BUILDKITE_TRIGGERED_FROM_BUILD_ID}
      - docker-compose#v3.7.0:
          build:
            - node-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-node-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push:
            - node-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-node-${BRANCH_NAME}

  - label: ':node: Node 4'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "4"

  - label: ':node: Node 6'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "6"

  - label: ':node: Node 8'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "8"

  - label: ':node: Node 10'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "10"

  - label: ':node: Node 12'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "12"

  - label: ':node: Node 14'
    depends_on: "node-maze-runner-image"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v3.7.0:
        run: node-maze-runner
        use-aliases: true
        verbose: true
    env:
      NODE_VERSION: "14"
