steps:

  #
  # Publish/package notifier
  #
  - label: ':docker: Prepare package.json'
    key: "package-js"
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.7.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  - label: ':docker: Build and publish JS packages'
    key: "publish-js"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js

  #
  # Trigger individual pipelines
  #
  - label: 'Trigger Browser pipeline'
    depends_on: "package-js"
    trigger: 'bugsnag-js-browsers'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger Node pipeline'
    depends_on: "package-js"
    trigger: 'bugsnag-js-node'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger Expo pipeline'
    depends_on: "publish-js"
    # TODO: Rename to bugsnag-js-expo
    trigger: 'at-bugsnag-expo'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger React Native pipeline'
    depends_on: "publish-js"
    # TODO: Rename to bugsnag-js-react-native
    trigger: 'at-bugsnag-react-native'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  #
  # Core tests and checks
  #

  - label: ':docker: Build CI image'
    key: "ci-image"
    depends_on: "package-js"
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.2.0:
          download: min_packages.tar
      - docker-compose#v3.7.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
      - docker-compose#v3.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base

  - label: 'Lint'
    depends_on: "ci-image"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.7.0:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    depends_on: "ci-image"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.7.0:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    depends_on: "ci-image"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.7.0:
        run: ci
    command: 'npm run test:types'
