steps:

  #
  # Android builder
  #
  - label: ':docker: Build RN Android Builder image'
    key: "android-builder-image"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.9.0:
          build: react-native-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.9.0:
          push: react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}

  #
  # Test fixtures
  #
  - label: ':android: Build RN 0.60 apk'
    key: "rn-0-60-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.60"
      LANG: "en_US.UTF-8"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/rn0.60.apk

  - label: ':ios: Build RN 0.60 ipa'
    key: "rn-0-60-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-mac-cocoa-10.15"
    env:
      REACT_NATIVE_VERSION: rn0.60
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode11.app"
    artifact_paths: build/rn0.60.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build RN 0.63 apk'
    key: "rn-0-63-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.63"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/rn0.63.apk

  - label: ':ios: Build RN 0.63 ipa'
    key: "rn-0-63-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      REACT_NATIVE_VERSION: rn0.63
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/rn0.63.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build RN 0.64 (Hermes) apk'
    key: "rn-0-64-hermes-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.64-hermes"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/rn0.64-hermes.apk

  - label: ':ios: Build RN 0.64 ipa'
    key: "rn-0-64-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      REACT_NATIVE_VERSION: rn0.64-hermes
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/rn0.64-hermes.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build react-navigation 0.60 apk'
    key: "react-navigation-0-60-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.60"
      JS_SOURCE_DIR: "react_navigation_js"
      ARTEFACT_NAME: "r_navigation_0.60"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/r_navigation_0.60.apk

  # See: PLAT-5173
  - label: ':ios: Build react-navigation 0.60 ipa'
    skip: "See PLAT-5173"
    key: "react-navigation-0-60-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-mac-cocoa-10.15"
    env:
      REACT_NATIVE_VERSION: rn0.60
      JS_SOURCE_DIR: "react_navigation_js"
      ARTEFACT_NAME: "r_navigation_0.60"
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode11.app"
    artifact_paths: build/r_navigation_0.60.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build react-navigation 0.63 apk'
    key: "react-navigation-0-63-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.63"
      JS_SOURCE_DIR: "react_navigation_js"
      ARTEFACT_NAME: "r_navigation_0.63"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/r_navigation_0.63.apk

  - label: ':ios: Build react-navigation 0.63 ipa'
    key: "react-navigation-0-63-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      REACT_NATIVE_VERSION: rn0.63
      JS_SOURCE_DIR: "react_navigation_js"
      ARTEFACT_NAME: "r_navigation_0.63"
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/r_navigation_0.63.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build react-native-navigation 0.60 apk'
    key: "react-native-navigation-0-60-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.60"
      JS_SOURCE_DIR: "react_native_navigation_js"
      ARTEFACT_NAME: "r_native_navigation_0.60"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/r_native_navigation_0.60.apk

  # See: PLAT-5173
  - label: ':ios: Build react-native-navigation 0.60 ipa'
    skip: "See PLAT-5173"
    key: "react-native-navigation-0-60-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-mac-cocoa-10.15"
    env:
      REACT_NATIVE_VERSION: rn0.60
      JS_SOURCE_DIR: "react_native_navigation_js"
      ARTEFACT_NAME: "r_native_navigation_0.60"
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode11.app"
    artifact_paths: build/r_native_navigation_0.60.ipa
    commands:
      - npm run test:build-react-native-ios

  - label: ':android: Build react-native-navigation 0.63 apk'
    key: "react-native-navigation-0-63-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.63"
      JS_SOURCE_DIR: "react_native_navigation_js"
      ARTEFACT_NAME: "r_native_navigation_0.63"
    plugins:
      - docker-compose#v3.9.0:
          run: react-native-android-builder
    artifact_paths:
      - build/r_native_navigation_0.63.apk

  # See: PLAT-5173
  - label: ':ios: Build react-native-navigation 0.63 ipa'
    skip: "See PLAT-5173"
    key: "react-native-navigation-0-63-ipa"
    timeout_in_minutes: 60
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      REACT_NATIVE_VERSION: rn0.63
      JS_SOURCE_DIR: "react_native_navigation_js"
      ARTEFACT_NAME: "r_native_navigation_0.63"
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode13.app"
    artifact_paths: build/r_native_navigation_0.63.ipa
    commands:
      - npm run test:build-react-native-ios

  #
  # End-to-end tests
  #
  - label: ':android: RN 0.60 Android 11 end-to-end tests'
    depends_on: "rn-0-60-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.60.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/rn0.60.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':ios: RN 0.60 iOS 12 end-to-end tests'
    depends_on: "rn-0-60-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.60.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/rn0.60.ipa
        - --farm=bs
        - --device=IOS_12
        - --a11y-locator
        - --appium-version=1.18.0
        - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: RN 0.63 Android 11 end-to-end tests'
    depends_on: "rn-0-63-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.63.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/rn0.63.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: RN 0.64 (Hermes) Android 11 end-to-end tests'
    depends_on: "rn-0-64-hermes-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.64-hermes.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/rn0.64-hermes.apk
          - --farm=bs
          - --device=ANDROID_11_0
          - --a11y-locator
          - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':ios: RN 0.63 iOS 12 end-to-end tests'
    depends_on: "rn-0-63-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.63.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/rn0.63.ipa
        - --farm=bs
        - --device=IOS_12
        - --a11y-locator
        - --appium-version=1.18.0
        - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':ios: RN 0.64 iOS 14 end-to-end tests'
    depends_on: "rn-0-64-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/rn0.64-hermes.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/rn0.64-hermes.ipa
          - --farm=bs
          - --device=IOS_14
          - --a11y-locator
          - --appium-version=1.18.0
          - --fail-fast
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: react-navigation 0.60 Android 11 end-to-end tests'
    depends_on: "react-navigation-0-60-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_navigation_0.60.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/r_navigation_0.60.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
        - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # See: PLAT-5173
  - label: ':ios: react-navigation 0.60 iOS 13 end-to-end tests'
    skip: "See PLAT-5173"
    depends_on: "react-navigation-0-60-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_navigation_0.60.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/r_navigation_0.60.ipa
          - --farm=bs
          - --device=IOS_12
          - --a11y-locator
          - --appium-version=1.18.0
          - --fail-fast
          - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: react-navigation 0.63 Android 11 end-to-end tests'
    depends_on: "react-navigation-0-63-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_navigation_0.63.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/r_navigation_0.63.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
        - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':ios: react-navigation 0.63 iOS 14 end-to-end tests'
    depends_on: "react-navigation-0-63-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_navigation_0.63.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/r_navigation_0.63.ipa
          - --farm=bs
          - --device=IOS_14
          - --a11y-locator
          - --appium-version=1.21.0
          - --fail-fast
          - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: react-native-navigation 0.60 Android 11 end-to-end tests'
    depends_on: "react-native-navigation-0-60-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_native_navigation_0.60.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/r_native_navigation_0.60.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
        - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # See: PLAT-5173
  - label: ':ios: react-native-navigation 0.60 iOS 13 end-to-end tests'
    skip: "See PLAT-5173"
    depends_on: "react-native-navigation-0-60-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_native_navigation_0.60.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/r_native_navigation_0.60.ipa
          - --farm=bs
          - --device=IOS_13
          - --appium-version=1.18.0
          - --a11y-locator
          - --fail-fast
          - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':android: react-native-navigation 0.63 Android 11 end-to-end tests'
    depends_on: "react-native-navigation-0-63-apk"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_native_navigation_0.63.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
        - --app=build/r_native_navigation_0.63.apk
        - --farm=bs
        - --device=ANDROID_11_0
        - --a11y-locator
        - --fail-fast
        - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  # See: PLAT-5173
  - label: ':ios: react-native-navigation 0.63 iOS 13 end-to-end tests'
    skip: "See PLAT-5173"
    depends_on: "react-native-navigation-0-63-ipa"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.5.0:
        download: "build/r_native_navigation_0.63.ipa"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        use-aliases: true
        command:
          - --app=build/r_native_navigation_0.63.ipa
          - --farm=bs
          - --device=IOS_13
          - --a11y-locator
          - --appium-version=1.18.0
          - --fail-fast
          - features/navigation.feature
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
