steps:

  - group: "React Native (Android) Tests"
    steps:
      #
      # Android builder
      #
      - label: ":docker: Build RN Android Builder image"
        key: "android-builder-image"
        timeout_in_minutes: 30
        plugins:
          - docker-compose#v4.12.0:
              build: react-native-android-builder
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from:  react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push: react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}

      #
      # Test fixtures
      #
      - label: ":android: Build RN 0.60 apk"
        key: "rn-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          LANG: "en_US.UTF-8"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.60.apk

      - label: ":android: Build RN 0.66 apk"
        key: "rn-0-66-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.66"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.66.apk

      - label: ":android: Build RN 0.67 apk"
        key: "rn-0-67-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.67"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.67.apk

      - label: ":android: Build RN 0.68 Hermes apk"
        key: "rn-0-68-hermes-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.68-hermes"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.68-hermes.apk

      - label: ":android: Build RN 0.69 apk"
        key: "rn-0-69-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.69"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/rn0.69.apk

      - label: ":android: Build react-navigation 0.60 apk"
        key: "react-navigation-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          JS_SOURCE_DIR: "react_navigation_js"
          ARTEFACT_NAME: "r_navigation_0.60"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/r_navigation_0.60.apk

      - label: ":android: Build react-navigation 0.66 apk"
        key: "react-navigation-0-66-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.66"
          JS_SOURCE_DIR: "react_navigation_js"
          ARTEFACT_NAME: "r_navigation_0.66"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/r_navigation_0.66.apk

      - label: ":android: Build react-native-navigation 0.60 apk"
        key: "react-native-navigation-0-60-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.60"
          JS_SOURCE_DIR: "react_native_navigation_js"
          ARTEFACT_NAME: "r_native_navigation_0.60"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/r_native_navigation_0.60.apk

      - label: ":android: Build react-native-navigation 0.66 apk"
        key: "react-native-navigation-0-66-apk"
        depends_on:
          - "android-builder-image"
        timeout_in_minutes: 60
        env:
          REACT_NATIVE_VERSION: "rn0.66"
          JS_SOURCE_DIR: "react_native_navigation_js"
          ARTEFACT_NAME: "r_native_navigation_0.66"
        plugins:
          - docker-compose#v4.12.0:
              run: react-native-android-builder
        artifact_paths:
          - build/r_native_navigation_0.66.apk

      #
      # End-to-end tests
      #
      - label: ":android: RN 0.60 Android 11 end-to-end tests"
        depends_on: "rn-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/rn0.60.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: RN 0.66 Android 11 end-to-end tests"
        depends_on: "rn-0-66-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.66.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/rn0.66.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: RN 0.67 Android 11 end-to-end tests"
        depends_on: "rn-0-67-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.67.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.67.apk
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: RN 0.69 Android 11 end-to-end tests"
        depends_on: "rn-0-69-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.69.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.69.apk
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: RN 0.68 (Hermes) Android 12 end-to-end tests"
        depends_on: "rn-0-68-hermes-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/rn0.68-hermes.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=build/rn0.68-hermes.apk
              - --farm=bb
              - --device=ANDROID_10|ANDROID_11|ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: react-navigation 0.60 Android 11 end-to-end tests"
        depends_on: "react-navigation-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_navigation_0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/r_navigation_0.60.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
            - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: react-navigation 0.66 Android 11 end-to-end tests"
        depends_on: "react-navigation-0-66-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_navigation_0.66.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/r_navigation_0.66.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
            - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: react-native-navigation 0.60 Android 11 end-to-end tests"
        depends_on: "react-native-navigation-0-60-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_native_navigation_0.60.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/r_native_navigation_0.60.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
            - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager

      - label: ":android: react-native-navigation 0.66 Android 11 end-to-end tests"
        depends_on: "react-native-navigation-0-66-apk"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "build/r_native_navigation_0.66.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
            - --app=build/r_native_navigation_0.66.apk
            - --farm=bb
            - --device=ANDROID_10|ANDROID_11|ANDROID_12
            - --a11y-locator
            - --fail-fast
            - --no-tunnel
            - --aws-public-ip
            - features/navigation.feature
        concurrency: 25
        concurrency_group: 'bitbar-app'
        concurrency_method: eager
