require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'reactnative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'reactnativeTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'reactnative-tvOS' do
  # Pods for reactnative-tvOS

  target 'reactnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
