require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rn0_63' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'rn0_63Tests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'rn0_63-tvOS' do
  # Pods for rn0_63-tvOS

  target 'rn0_63-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
