FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base

# Java version
ARG JAVA_VERSION
ENV JAVA_HOME=/usr/local/openjdk-${JAVA_VERSION}

ARG NODE_VERSION
ENV NODE_VERSION=$NODE_VERSION
RUN curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
RUN apt-get install -y nodejs rsync

RUN npm i -g run-func

WORKDIR /app

# npm auth
RUN rm -f ~/.npmrc
ARG REG_BASIC_CREDENTIAL
ARG REG_NPM_EMAIL
ARG REGISTRY_URL
RUN echo "registry=$REGISTRY_URL" >> ~/.npmrc
RUN echo "_auth=$REG_BASIC_CREDENTIAL" >> ~/.npmrc
RUN echo "email=$REG_NPM_EMAIL" >> ~/.npmrc
RUN echo "always-auth=true" >> ~/.npmrc

# fix npm auth config for node 18
RUN if [ "$NODE_VERSION" = "18" ]; then npm config fix; fi

# gradle / artifactory auth
ARG MAVEN_REPO_URL
ENV MAVEN_REPO_URL="$MAVEN_REPO_URL"
ENV MAVEN_REPO_CREDS="$REG_BASIC_CREDENTIAL"

# Now copy in all the files needed to build
COPY .git .git
COPY lerna.json .
COPY scripts/common.js scripts/react-native-helper.js scripts/

# Do a full build by running the container
CMD run-func scripts/react-native-helper.js buildAndroid "/app/test/react-native/features/fixtures" "/app/features/fixtures"
