# CI test image for building the CLI
FROM node:lts-alpine as react-native-cli-feature-builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY babel.config.js lerna.json .eslintignore .eslintrc.js jest.config.js tsconfig.json packages/expo/unimodules-core.d.ts ./
COPY bin ./bin
COPY packages ./packages

RUN npm run bootstrap

RUN npx lerna run build --scope @bugsnag/react-native-cli
RUN npm pack --verbose packages/react-native-cli/

# The maze-runner test image
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v6-cli as react-native-cli-maze-runner

WORKDIR /app

COPY test/react-native-cli/features test/react-native-cli/features
COPY test/react-native-cli/scripts test/react-native-cli/scripts

# TODO install this from Artifactory in future
COPY --from=react-native-cli-feature-builder /app/bugsnag-react-native-cli-*.tgz ./
RUN for d in test/react-native-cli/features/fixtures/*/; do cp /app/*.tgz "$d"; done

WORKDIR /app/test/react-native-cli

ENTRYPOINT ["bundle", "exec", "maze-runner"]
