# CI test image for unit/lint/type tests
#FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v3-cli
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:tms-appium-for-ios-cli
COPY /test/react-native /app/test/react-native
WORKDIR /app/test/react-native

ENTRYPOINT ["bundle", "exec", "maze-runner"]
