FROM openjdk:8-jdk-stretch

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update
RUN apt-get install -y gradle jq git-core curl build-essential openssl libssl-dev nodejs

WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q
RUN unzip -q sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools"

ENV PATH="${PATH}:/sdk/platform-tools"
ENV ANDROID_HOME="/sdk/"

WORKDIR /app

ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"

COPY test/react-native/features /app/features