# CI test image for unit/lint/type tests
FROM node:12-alpine

RUN apk add --update bash

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY babel.config.js tslint.json lerna.json ./
ADD min_packages.tar packages
COPY bin ./bin
RUN npx lerna bootstrap
COPY packages ./packages
RUN npm run build
