FROM openjdk:8-jdk-stretch

# OS setup
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update
RUN apt-get install -y gradle jq git-core curl build-essential openssl libssl-dev nodejs

# Android tools
WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q \
    && unzip -q sdk-tools-linux-4333796.zip \
    && rm sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools" "build-tools;28.0.3"
ENV PATH="${PATH}:/sdk/platform-tools"

ENV ANDROID_HOME="/sdk/"

WORKDIR /app

ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"

ARG REACT_NATIVE_VERSION
ENV REACT_NATIVE_FIXTURE=${REACT_NATIVE_VERSION}

COPY .git .git
COPY scripts/ scripts/
COPY lerna.json .


# npm auth
RUN rm -f ~/.npmrc
ARG REG_BASIC_CREDENTIAL
ARG REG_NPM_EMAIL
RUN echo "_auth=$REG_BASIC_CREDENTIAL" >> ~/.npmrc
RUN echo "email=$REG_NPM_EMAIL" >> ~/.npmrc
RUN echo "always-auth=true" >> ~/.npmrc


# RN shell


# Branch specific stuff


RUN cp -r /app/features/fixtures/app/ /app/features/fixtures/${REACT_NATIVE_VERSION}/app/

WORKDIR /app/features/fixtures/${REACT_NATIVE_VERSION}
RUN ./gradlew

COPY test/react-native/features /app/features

# npm install
ARG REGISTRY_URL
RUN npm install --registry $REGISTRY_URL
ARG BUILDKITE
ARG BRANCH_NAME
RUN BUILDKITE=${BUILDKITE} BRANCH_NAME=${BRANCH_NAME} node scripts/install.js $REGISTRY_URL

RUN ./node_modules/.bin/react-native link

WORKDIR /app/features/fixtures/${REACT_NATIVE_VERSION}/android

# Finally, build the test fixture
CMD ./gradlew assembleRelease && \
    cp /app/features/fixtures/$REACT_NATIVE_FIXTURE/android/app/build/outputs/apk/release/app-release.apk /app/build/$REACT_NATIVE_FIXTURE.apk
