# CI test image for unit/lint/type tests
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:tms-use-maze-check-cli as expo-maze-runner
COPY /test/expo/features /app/test/expo/features
COPY /test/expo/scripts /app/test/expo/scripts
WORKDIR /app/test/expo
