steps:

  - group: ":cloudflare: Cloudflare Worker Tests"
    steps:
    - label: ":cloudflare: Cloudflare Worker tests"
      timeout_in_minutes: 40
      agents:
        queue: macos-15
      env:
        NODE_VERSION: "22"
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
        VERBOSE: "1"
      commands:
        - "cd test/cloudflare-workers"
        - "bundle install"
        - "bundle exec maze-runner"
