steps:
  - label: "Electron {{matrix.electron_version}} tests - macOS - Node {{matrix.node_version}}"
    timeout_in_minutes: 40
    agents:
      queue: macos-14
    env:
      NODE_VERSION: "{{matrix.node_version}}"
      ELECTRON_VERSION: "{{matrix.electron_version}}"
    matrix:
      setup:
        electron_version:
          - "^20.0.0"
          - "^24.0.0"
          - "^26.0.0"
          - "^28.0.0"
          - "^30.0.0"
        node_version:
          - "18"
    commands:
      - echo "Running on Node `node -v`"
      - npm install electron@${ELECTRON_VERSION} --no-audit --progress=false --no-save
      - npm ci --no-audit --progress=false
      - npx lerna bootstrap
      - npm run build:electron
      - defaults write com.apple.CrashReporter DialogType none
      - npm run test:unit:electron-runner
      - npm run test:electron

  #
  # Ubuntu tests Node 18
  #
  - label: "Build Electron {{matrix.electron_version}} docker test image"
    timeout_in_minutes: 10
    env:
      ELECTRON_VERSION: "{{matrix.electron_version}}"
    matrix:
      setup:
        electron_version:
          - "^20.0.0"
          - "^24.0.0"
          - "^26.0.0"
          - "^28.0.0"
          - "^30.0.0"
    plugins:
      - docker-compose#v4.12.0:
          build:
            - electron-test-image
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - electron-test-image:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-electron-test-${BRANCH_NAME}-${matrix.electron_version}
      # - docker-compose#v4.12.0:
      #     push:
      #       - electron-ubuntu-test:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-electron-test-${BRANCH_NAME}-${matrix.electron_version}

  # - label: "Electron ${{matrix.electron_version}} linting"
  #   timeout_in_minutes: 10
  #   env:
  #     ELECTRON_VERSION: "${{matrix.electron_version}}"
  #   matrix:
  #     setup:
  #       electron_version:
  #         - "^20.0.0"
  #         - "^24.0.0"
  #         - "^26.0.0"
  #         - "^28.0.0"
  #         - "^30.0.0"
  #   plugins:
  #     - docker-compose#v4.12.0:
  #         run: electron-test-image
  #         command: npm run test:lint-native

  # - label: "Electron {{matrix.electron_version}} unit tests"
  #   timeout_in_minutes: 10
  #   env:
  #     ELECTRON_VERSION: "{{matrix.electron_version}}"
  #   matrix:
  #     setup:
  #       electron_version:
  #         - "^20.0.0"
  #         - "^24.0.0"
  #         - "^26.0.0"
  #         - "^28.0.0"
  #         - "^30.0.0"
  #   plugins:
  #     - docker-compose#v4.12.0:
  #         run: electron-test-image
  #         command: npm run test:unit:electron-runner

  # - label: "Electron {{matrix.electron_version}} integration tests"
  #   timeout_in_minutes: 10
  #   env:
  #     ELECTRON_VERSION: "{{matrix.electron_version}}"
  #   matrix:
  #     setup:
  #       electron_version:
  #         - "^20.0.0"
  #         - "^24.0.0"
  #         - "^26.0.0"
  #         - "^28.0.0"
  #         - "^30.0.0"
  #   plugins:
  #     - docker-compose#v4.12.0:
  #         run: electron-test-image
  #         command: npm run test:electron
  #   artifact_paths:
  #       - "test/electron/maze_output/**/*"
