steps:

  - group: ":electron: Electron Tests"
    steps:
    - label: "Electron {{matrix.electron_version}} tests - macOS - Node {{matrix.node_version}}"
      timeout_in_minutes: 40
      agents:
        queue: macos-15-isolated
      env:
        NODE_VERSION: "{{matrix.node_version}}"
        ELECTRON_VERSION: "{{matrix.electron_version}}"
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
        START_LOCAL_NPM: "1"
        VERBOSE: "1"
      matrix:
        setup:
          electron_version:
            - "^38.0.0" # Latest Version
            - "^37.0.0" # EOL 2026-Jan-13
            - "^36.0.0" # EOL 2025-Oct-28
          node_version:
            - "22"
        adjustments:
          - with:
              electron_version: "^34.0.0" # EOL 2025-Jun-24
              node_version: "20"
          - with:
              electron_version: "^32.0.0" # EOL 2025-Mar-04
              node_version: "20"
          - with:
              electron_version: "^30.0.0" # EOL 2024-Oct-15
              node_version: "20"
      commands:
        - echo "Running on Node `node -v`"
        - npm install electron@${ELECTRON_VERSION} --no-audit --progress=false --no-save
        - npm ci --no-audit --progress=false
        - npm run build:electron
        - defaults write com.apple.CrashReporter DialogType none
        - npm run test:unit:electron-runner
        - npm run test:electron
