agents:
  queue: "opensource"

steps:
  group: ":expo: Expo Tests"
  steps:
    - label: "@bugsnag/expo latest"
      depends_on: "publish-js"
      trigger: "bugsnag-expo"
      build:
        branch: "v52/next"
        env:
          BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
          BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
          # a branch name that's safe to use as a docker cache identifier
          BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"

    - label: "@bugsnag/expo v51/next"
      depends_on: "publish-js"
      trigger: "bugsnag-expo"
      build:
        branch: "v51/next"
        env:
          BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
          BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
          # a branch name that's safe to use as a docker cache identifier
          BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"

    - label: "@bugsnag/expo v50/next"
      depends_on: "publish-js"
      trigger: "bugsnag-expo"
      build:
        branch: "v50/next"
        env:
          BUGSNAG_JS_BRANCH: "${BUILDKITE_BRANCH}"
          BUGSNAG_JS_COMMIT: "${BUILDKITE_COMMIT}"
          # a branch name that's safe to use as a docker cache identifier
          BUGSNAG_JS_CACHE_SAFE_BRANCH_NAME: "${BRANCH_NAME}"
