agents:
  queue: "opensource"

steps:

  - group: "React Native (iOS) Tests"
    steps:

      #
      # Test fixtures
      #
      - label: ":ios: Build RN 0.68 Hermes ipa"
        key: "rn-0-68-hermes-ipa"
        depends_on: "publish-js"
        timeout_in_minutes: 20
        agents:
          queue: "macos-12-arm"
        env:
          REACT_NATIVE_VERSION: rn0.68-hermes
          LANG: "en_US.UTF-8"
          DEVELOPER_DIR: "/Applications/Xcode14.app"
        artifact_paths: build/rn0.68-hermes.ipa
        commands:
          - npm run test:build-react-native-ios
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ":ios: Build RN 0.69 ipa"
        key: "rn-0-69-ipa"
        depends_on: "publish-js"
        timeout_in_minutes: 20
        agents:
          queue: "macos-12-arm"
        env:
          REACT_NATIVE_VERSION: rn0.69
          LANG: "en_US.UTF-8"
          DEVELOPER_DIR: "/Applications/Xcode14.app"
        artifact_paths: build/rn0.69.ipa
        commands:
          - npm run test:build-react-native-ios
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':mac: Build RN {{matrix}} test fixture ipa (Old Arch)'
        key: "build-react-native-ios-fixture-old-arch-full"
        depends_on: "publish-js"
        timeout_in_minutes: 30
        agents:
          queue: "macos-14"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          BUILD_IOS: "true"
          XCODE_VERSION: "15.3.0"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/old-arch/**/output/reactnative.ipa"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.77"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':mac: Build RN {{matrix}} test fixture ipa (New Arch)'
        key: "build-react-native-ios-fixture-new-arch-full"
        depends_on: "publish-js"
        timeout_in_minutes: 30
        agents:
          queue: "macos-14"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_IOS: "true"
          XCODE_VERSION: "15.3.0"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/new-arch/**/output/reactnative.ipa"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.77"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':mac: Build react-native-navigation {{matrix}} test fixture ipa (Old Arch)'
        key: "build-react-native-navigation-ios-fixture-old-arch"
        depends_on: "publish-js"
        timeout_in_minutes: 30
        agents:
          queue: "macos-14"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          BUILD_IOS: "true"
          XCODE_VERSION: "15.3.0"
          REACT_NATIVE_NAVIGATION: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/react-native-navigation/old-arch/**/output/reactnative.ipa"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          - "0.71"
          - "0.72"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      # Skipped due to build failures with react-native-navigation when new arch is enabled
      # TODO: Investigate and try to re-enable when we add tests for more recent React Native versions
      # - label: ':mac: Build react-native-navigation {{matrix}} test fixture ipa (New Arch)'
      #   key: "build-react-native-navigation-ios-fixture-new-arch"
      #   timeout_in_minutes: 30
      #   agents:
      #     queue: "macos-14"
      #   env:
      #     NODE_VERSION: "18"
      #     RN_VERSION: "{{matrix}}"
      #     RCT_NEW_ARCH_ENABLED: "1"
      #     BUILD_IOS: "true"
      #     XCODE_VERSION: "15.3.0"
      #     REACT_NATIVE_NAVIGATION: "true"
      #   artifact_paths:
      #     - "test/react-native/features/fixtures/generated/react-native-navigation/new-arch/**/output/reactnative.ipa"
      #   commands:
      #     - "bundle install"
      #     - "node scripts/generate-react-native-fixture.js"
      #   matrix:
      #     - "0.71"
      #     - "0.72"
      #   retry:
      #     automatic:
      #       - exit_status: "*"
      #         limit: 1

      #
      # End-to-end tests
      #
      - label: ":bitbar: :ios: RN 0.68 (hermes) iOS end-to-end tests"
        depends_on: "rn-0-68-hermes-ipa"
        timeout_in_minutes: 40
        plugins:
          artifacts#v1.5.0:
            download: "build/rn0.68-hermes.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            use-aliases: true
            command:
              - --app=build/rn0.68-hermes.ipa
              - --farm=bb
              - --device=IOS_15|IOS_16
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 5
        concurrency_group: "browserstack-app"
        concurrency_method: eager

      - label: ":bitbar: :ios: RN 0.69 iOS end-to-end tests"
        depends_on: "rn-0-69-ipa"
        timeout_in_minutes: 40
        plugins:
          artifacts#v1.5.0:
            download: "build/rn0.69.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            use-aliases: true
            command:
              - --app=build/rn0.69.ipa
              - --farm=bb
              - --device=IOS_15|IOS_16
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        env:
          SKIP_NAVIGATION_SCENARIOS: "true"
          HERMES: "true"
        concurrency: 5
        concurrency_group: "browserstack-app"
        concurrency_method: eager
      
      - label: ":bitbar: :mac: RN {{matrix}} iOS (Old Arch) end-to-end tests"
        depends_on: "build-react-native-ios-fixture-old-arch-full"
        timeout_in_minutes: 40
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/old-arch/{{matrix}}/output/reactnative.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/old-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_15
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
        env:
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.77"

      - label: ":bitbar: :mac: RN {{matrix}} iOS (New Arch) end-to-end tests"
        depends_on: "build-react-native-ios-fixture-new-arch-full"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/new-arch/{{matrix}}/output/reactnative.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/new-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_15
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          RN_VERSION: "{{matrix}}"
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.77"

      # current latest version (v7.40.1) of react-native-navigation's autolinking tool doesn't currently support RN 0.73+,
      # causing a build failure - see https://github.com/wix/react-native-navigation/issues/7821
      # TODO: Investigate and try to re-enable when we add tests for more recent React Native versions
      - label: ":bitbar: :mac: react-native-navigation {{matrix}} iOS (Old Arch) end-to-end tests"
        depends_on: "build-react-native-navigation-ios-fixture-old-arch"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/react-native-navigation/old-arch/{{matrix}}/output/reactnative.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/react-native-navigation/old-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_15
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/react-native-navigation.feature
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
        env:
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          REACT_NATIVE_NAVIGATION: "true"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.71"
          - "0.72"

      # Skipped due to build failures with react-native-navigation when new arch is enabled
      # TODO: Investigate and try to re-enable when we add tests for more recent React Native versions
      # - label: ":bitbar: :mac: react-native-navigation {{matrix}} iOS (New Arch) end-to-end tests"
      #   depends_on: "build-react-native-navigation-ios-fixture-new-arch"
      #   timeout_in_minutes: 60
      #   plugins:
      #     artifacts#v1.9.0:
      #       download: "test/react-native/features/fixtures/generated/react-native-navigation/new-arch/{{matrix}}/output/reactnative.ipa"
      #       upload: ./test/react-native/maze_output/**/*
      #     docker-compose#v4.12.0:
      #       pull: react-native-maze-runner
      #       run: react-native-maze-runner
      #       service-ports: true
      #       command:
      #         - --app=/app/features/fixtures/generated/react-native-navigation/new-arch/{{matrix}}/output/reactnative.ipa
      #         - --farm=bb
      #         - --device=IOS_15
      #         - --fail-fast
      #         - --no-tunnel
      #         - --aws-public-ip
      #         - features/react-native-navigation.feature
      #     test-collector#v1.10.2:
      #       files: "reports/TEST-*.xml"
      #       format: "junit"
      #       branch: "^main|next$$"
      #       api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
      #   env:
      #     RCT_NEW_ARCH_ENABLED: "1"
      #     RN_VERSION: "{{matrix}}"
      #     REACT_NATIVE_NAVIGATION: "true"
      #   retry:
      #     manual:
      #       permit_on_passed: true
      #   concurrency: 25
      #   concurrency_group: "bitbar"
      #   concurrency_method: eager
      #   matrix:
      #     - "0.71"
      #     - "0.72"
