agents:
  queue: opensource

steps:

  - group: "React Native (Android) Tests"
    steps:
      #
      # Test fixture builds
      #
      - label: ':android: Build RN {{matrix.reactnative}} test fixture APK (Old Arch)'
        key: "build-react-native-android-fixture-old-arch-full"
        timeout_in_minutes: 15
        agents:
          queue: macos-node-18
        env:
          JAVA_VERSION: "{{matrix.java}}"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix.reactnative}}"
          RCT_NEW_ARCH_ENABLED: "0"
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/old-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          setup:
            reactnative:
              - "0.72"
              - "0.74"
              - "0.76"
              - "0.78"
              - "0.79"
            java:
              - "17"
          adjustments:
            - with:
                reactnative: "0.68"
                java: "11"
            - with:
                reactnative: "0.69"
                java: "11"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':android: Build RN {{matrix}} test fixture APK (New Arch)'
        key: "build-react-native-android-fixture-new-arch-full"
        timeout_in_minutes: 15
        agents:
          queue: macos-node-18
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/new-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.78"
          - "0.79"

      - label: ':android: Build react-native-navigation {{matrix}} test fixture APK (Old Arch)'
        key: "build-react-native-navigation-android-fixture-old-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-node-18
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          BUILD_ANDROID: "true"
          REACT_NATIVE_NAVIGATION: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/react-native-navigation/old-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          - "0.72"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':android: Build react-native-navigation {{matrix}} test fixture APK (New Arch)'
        key: "build-react-native-navigation-android-fixture-new-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-node-18
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_ANDROID: "true"
          REACT_NATIVE_NAVIGATION: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/react-native-navigation/new-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1
        matrix:
          - "0.72"

      #
      # End-to-end tests
      #
      - label: ":bitbar: :android: RN {{matrix}} Android 12 (Old Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-old-arch-full"
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        env:
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.68"
          - "0.69"
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.78"
          - "0.79"

      # current latest version (v7.40.1) of react-native-navigation's autolinking tool doesn't support RN 0.73+,
      # causing a build failure - see https://github.com/wix/react-native-navigation/issues/7821
      # TODO: Investigate and try to re-enable when we add tests for more recent React Native versions
      - label: ":bitbar: :android: RN {{matrix}} Android 12 (New Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-new-arch-full"
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          RN_VERSION: "{{matrix}}"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.72"
          - "0.74"
          - "0.76"
          - "0.78"
          - "0.79"

      - label: ":bitbar: :android: react-native-navigation {{matrix}} Android 12 (Old Arch) end-to-end tests"
        depends_on: "build-react-native-navigation-android-fixture-old-arch"
        timeout_in_minutes: 10
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/react-native-navigation/old-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/react-native-navigation/old-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/react-native-navigation.feature
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        env:
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          REACT_NATIVE_NAVIGATION: "true"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.72"

      - label: ":bitbar: :android: react-native-navigation {{matrix}} Android 12 (New Arch) end-to-end tests"
        depends_on: "build-react-native-navigation-android-fixture-new-arch"
        timeout_in_minutes: 10
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/react-native-navigation/new-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/react-native-navigation/new-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
              - features/react-native-navigation.feature
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          RN_VERSION: "{{matrix}}"
          REACT_NATIVE_NAVIGATION: "true"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.72"
