steps:

  - group: "React Native (Android) Tests"
    steps:
      - label: ':android: Build RN {{matrix}} test fixture APK (Old Arch)'
        key: "build-react-native-android-fixture-old-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-14
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/old-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        matrix:
          - "0.75"
          - "0.76"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':android: Build RN {{matrix}} test fixture APK (New Arch)'
        key: "build-react-native-android-fixture-new-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-14
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/new-arch/**/reactnative.apk"
        commands:
          - "bundle install"
          - "node scripts/generate-react-native-fixture.js"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1
        matrix:
          - "0.75"
          - "0.76"

      #
      # End-to-end tests
      #
      - label: ":bitbar: :android: RN {{matrix}} Android 12 (Old Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-old-arch"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
        env:
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "0"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.75"
          - "0.76"

      - label: ":bitbar: :android: RN {{matrix}} Android 12 (New Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-new-arch"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --appium-version=1.22
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_BUILDKITE_ANALYTICS_TOKEN"
        retry:
          manual:
            permit_on_passed: true
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          RN_VERSION: "{{matrix}}"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.75"
          - "0.76"

