name: AWS Lambda tests

permissions: read-all

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install net-tools

    - run: sam --version

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Install Ruby
      uses: ruby/setup-ruby@cb0fda56a307b8c78d38320cd40d9eb22a3bf04e
      with:
        ruby-version: '3.1'

    - name: Install Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: 18

    - name: Run tests
      run: |
        cd test/aws-lambda
        bundle install
        bundle exec maze-runner
