name: AWS Lambda tests

permissions: read-all

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install net-tools

    - run: sam --version

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Install Ruby
      uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
      with:
        ruby-version: '3.1'

    - name: Install Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: 18

    - name: Run tests
      run: |
        cd test/aws-lambda
        bundle install
        bundle exec maze-runner
