name: update-dependencies
permissions: read-all

on:
  repository_dispatch:
    types: [update-dependency]
  workflow_dispatch:
    inputs:
      target_submodule:
        description: 'Submodule to update'
        required: true
        type: string
      target_version:
        description: 'Version of the submodule to update to'
        required: true
        type: string

jobs:
  update-dependencies:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      SUBMODULE: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.target_submodule || inputs.target_submodule }}
      VERSION: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.target_version || inputs.target_version }}
      BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REVIEWER: gingerbenw
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: next

      - run: |
          git config --global user.name 'Bumpsnag bot'
          git config --global user.email ''

      - run: git fetch --prune --unshallow
      - run: git submodule update --init --recursive

      - name: Install ruby
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Update references locally
        run: TARGET_SUBMODULE=$SUBMODULE TARGET_VERSION=$VERSION bundle exec scripts/update-dependencies.rb

      - name: Commit and push changes
        run: BUMPSNAG_TARGET_HEADING="[Unreleased]" bundle exec bumpsnag commit-update $SUBMODULE $VERSION

      - name: List current branch name
        id: current-branch
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Create pull request
        if: ${{ steps.current-branch.outputs.branch != 'next'}}
        run: >
         gh pr create -B next
         -H bumpsnag-$SUBMODULE-$VERSION
         --title "Update $SUBMODULE to version $VERSION"
         --body 'Created by bumpsnag'
         --reviewer $REVIEWER
